"""add prospect_research (TASK-025)

Revision ID: f01144d07b48
Revises: 8af9ad2d52fb
Create Date: 2026-10-04 05:58:52.389367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f01144d07b48'
down_revision: Union[str, Sequence[str], None] = '8af9ad2d52fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prospect_research',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('target_type', sa.Enum('PROSPECT', 'CUSTOMER', name='research_target_type'), nullable=False),
    sa.Column('target_name', sa.String(length=200), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.Column('source_type', sa.Enum('COMPANY_SITE', 'NEWS', 'JOB_POSTING', 'INDUSTRY_SITE', 'PRODUCT_INFO', 'OTHER', name='research_source_type'), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=False, comment='用户提供的公开资料原文；AI 只能从中抽取事实'),
    sa.Column('facts_json', sa.JSON(), nullable=True, comment='公开事实；每条必须带原文逐字引用 quote'),
    sa.Column('inferences_json', sa.JSON(), nullable=True, comment='AI 推断；显式标注，不得伪装成事实'),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('draft_status', sa.Enum('NONE', 'GENERATED', 'CONFIRMED', 'REJECTED', name='research_draft_status'), nullable=False),
    sa.Column('drafts_json', sa.JSON(), nullable=True, comment='AI 生成的话术候选；需人工确认后才可用'),
    sa.Column('confirmed_by', sa.String(length=64), nullable=True, comment='确认人（登录用户名）'),
    sa.Column('confirmed_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.Column('source_type_evidence', sa.String(length=32), nullable=False, comment='本次研究的来源类型（MANUAL=人工提供资料）'),
    sa.Column('llm_called', sa.Boolean(), nullable=False, comment='本次是否真的调用了模型'),
    sa.Column('llm_error', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prospect_research_customer', 'prospect_research', ['customer_id'], unique=False)
    op.create_index('ix_prospect_research_status', 'prospect_research', ['draft_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prospect_research_status', table_name='prospect_research')
    op.drop_index('ix_prospect_research_customer', table_name='prospect_research')
    op.drop_table('prospect_research')
    # ### end Alembic commands ###
