"""add opportunities (D28 unfreeze)

Revision ID: 7c1a033e3f26
Revises: 8c41f0b27d55
Create Date: 2026-10-04 02:23:01.274298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7c1a033e3f26'
down_revision: Union[str, Sequence[str], None] = '8c41f0b27d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False, comment='所属客户；客户删除则其商机一并清除'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='商机名称，如「H800 采购意向」'),
    sa.Column('stage', sa.Enum('NEW', 'CONTACTED', 'QUALIFIED', 'VALIDATING', 'QUOTED', 'NEGOTIATING', 'WON', 'CLOSED_LOST', name='opportunity_stage'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='opportunity_priority'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='预计金额；NULL = 还没估出来（不是 0）'),
    sa.Column('currency', sa.String(length=8), nullable=False, comment='币种代码；★ 不做汇率换算'),
    sa.Column('won_amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='实际成交金额；未赢单为 NULL'),
    sa.Column('probability', sa.Integer(), nullable=True, comment='赢单概率 0~100；★ 由人工填写，不是模型预测（§三）'),
    sa.Column('expected_close_date', sa.Date(), nullable=True, comment='预计成交日；NULL = 未定'),
    sa.Column('closed_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True, comment='赢单/丢单时间'),
    sa.Column('owner', sa.String(length=64), nullable=True, comment='负责人（V1 存名字文本）'),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='软删除；不用物理删除以保留历史'),
    sa.Column('evidence_ref', sa.String(length=128), nullable=True, comment='证据锚点 = opportunity:{id}'),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_opportunities_customer', 'opportunities', ['customer_id'], unique=False)
    op.create_index('ix_opportunities_stage', 'opportunities', ['stage'], unique=False)
    op.create_index('ix_opportunities_stage_expected', 'opportunities', ['stage', 'expected_close_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_opportunities_stage_expected', table_name='opportunities')
    op.drop_index('ix_opportunities_stage', table_name='opportunities')
    op.drop_index('ix_opportunities_customer', table_name='opportunities')
    op.drop_table('opportunities')
    # ### end Alembic commands ###
