"""add data_connections and sync_records (D28 unfreeze)

Revision ID: 8af9ad2d52fb
Revises: 8a5c1f3b90d2
Create Date: 2026-10-04 05:17:55.884687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8af9ad2d52fb'
down_revision: Union[str, Sequence[str], None] = '8a5c1f3b90d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_connections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.Enum('EXCEL_CSV', 'MYSQL', 'POSTGRESQL', 'CRM', 'ERP', 'WECHAT_WORK', 'WEBSITE', 'API', 'WEBHOOK', name='connector_kind'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='展示名，如「生产库只读」'),
    sa.Column('status', sa.Enum('UNCONFIGURED', 'CONFIGURED', 'OK', 'ERROR', 'DISABLED', name='connection_status'), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True, comment='非敏感配置（host/port/database/table/file_type…）'),
    sa.Column('secret_encrypted', sa.Text(), nullable=True, comment='加密后的凭据；对外只返回是否已配置，绝不回显'),
    sa.Column('scope_note', sa.String(length=255), nullable=True),
    sa.Column('permission_note', sa.String(length=255), nullable=True),
    sa.Column('last_sync_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('last_test_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_data_connections_kind', 'data_connections', ['kind'], unique=False)
    op.create_table('sync_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('connection_id', sa.BigInteger(), nullable=False),
    sa.Column('trigger', sa.Enum('MANUAL', 'SCHEDULED', 'WEBHOOK', 'UPLOAD', name='sync_trigger'), nullable=False),
    sa.Column('result', sa.Enum('SUCCESS', 'PARTIAL', 'FAILED', name='sync_result'), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_created', sa.Integer(), nullable=False),
    sa.Column('rows_skipped', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.BigInteger(), nullable=True),
    sa.Column('message', sa.String(length=512), nullable=True, comment='结果说明/失败原因'),
    sa.Column('started_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['data_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_records_connection', 'sync_records', ['connection_id'], unique=False)
    op.create_index('ix_sync_records_started', 'sync_records', ['started_at'], unique=False)
    op.alter_column('customer_events', 'source_type',
               existing_type=mysql.ENUM('REAL', 'IMPORT', 'SYNC', 'WEB', 'TEST', 'DEMO', 'MANUAL', 'SYSTEM', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('MANUAL', 'IMPORT', 'SYSTEM', name='customer_event_source_type'),
               existing_nullable=False)
    op.alter_column('customer_handover_events', 'source_type',
               existing_type=mysql.ENUM('REAL', 'IMPORT', 'SYNC', 'WEB', 'TEST', 'DEMO', 'MANUAL', 'SYSTEM', collation='utf8mb4_unicode_ci'),
               comment='数据来源：人工操作=MANUAL；代码层判定=SYSTEM',
               existing_nullable=False)
    op.alter_column('customer_messages', 'source_type',
               existing_type=mysql.ENUM('REAL', 'IMPORT', 'SYNC', 'WEB', 'TEST', 'DEMO', 'MANUAL', 'SYSTEM', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('MANUAL', 'IMPORT', 'SYSTEM', name='message_source_type'),
               comment='写库必带：MANUAL=人工 / IMPORT=导入 / SYSTEM=系统',
               existing_nullable=False)
    op.alter_column('customer_messages', 'triggered_event_ref',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               comment='本条消息触发的业务事件锚点（如 customer_event:12）；NULL=未触发',
               existing_comment='本条消息触发的业务事件锚点；NULL=未触发',
               existing_nullable=True)
    op.alter_column('reports', 'generated_by',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='生成者；TASK-019 起可记登录用户名',
               existing_comment='V1 无登录体系，固定 system',
               existing_nullable=False)
    op.alter_column('risk_events', 'source_type',
               existing_type=mysql.ENUM('REAL', 'IMPORT', 'SYNC', 'WEB', 'TEST', 'DEMO', 'MANUAL', 'SYSTEM', collation='utf8mb4_unicode_ci'),
               comment='风险由什么产生：IMPORT=导入数据 / MANUAL=人工 / SYSTEM=代码判定',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('risk_events', 'source_type',
               existing_type=mysql.ENUM('REAL', 'IMPORT', 'SYNC', 'WEB', 'TEST', 'DEMO', 'MANUAL', 'SYSTEM', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='风险由什么产生：IMPORT=导入数据 / MANUAL=人工 / SYSTEM=代码判定',
               existing_nullable=False)
    op.alter_column('reports', 'generated_by',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='V1 无登录体系，固定 system',
               existing_comment='生成者；TASK-019 起可记登录用户名',
               existing_nullable=False)
    op.alter_column('customer_messages', 'triggered_event_ref',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               comment='本条消息触发的业务事件锚点；NULL=未触发',
               existing_comment='本条消息触发的业务事件锚点（如 customer_event:12）；NULL=未触发',
               existing_nullable=True)
    op.alter_column('customer_messages', 'source_type',
               existing_type=sa.Enum('MANUAL', 'IMPORT', 'SYSTEM', name='message_source_type'),
               type_=mysql.ENUM('REAL', 'IMPORT', 'SYNC', 'WEB', 'TEST', 'DEMO', 'MANUAL', 'SYSTEM', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='写库必带：MANUAL=人工 / IMPORT=导入 / SYSTEM=系统',
               existing_nullable=False)
    op.alter_column('customer_handover_events', 'source_type',
               existing_type=mysql.ENUM('REAL', 'IMPORT', 'SYNC', 'WEB', 'TEST', 'DEMO', 'MANUAL', 'SYSTEM', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='数据来源：人工操作=MANUAL；代码层判定=SYSTEM',
               existing_nullable=False)
    op.alter_column('customer_events', 'source_type',
               existing_type=sa.Enum('MANUAL', 'IMPORT', 'SYSTEM', name='customer_event_source_type'),
               type_=mysql.ENUM('REAL', 'IMPORT', 'SYNC', 'WEB', 'TEST', 'DEMO', 'MANUAL', 'SYSTEM', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.drop_index('ix_sync_records_started', table_name='sync_records')
    op.drop_index('ix_sync_records_connection', table_name='sync_records')
    op.drop_table('sync_records')
    op.drop_index('ix_data_connections_kind', table_name='data_connections')
    op.drop_table('data_connections')
    # ### end Alembic commands ###
