"""add real presence heartbeat fields (TASK-040)

Revision ID: e4af6ac94828
Revises: f077eb002a48
Create Date: 2026-10-08 03:46:53.173676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e4af6ac94828'
down_revision: Union[str, Sequence[str], None] = 'f077eb002a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True))
    op.add_column('users', sa.Column('last_active_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True))
    op.add_column('users', sa.Column('presence_override_until', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'presence_override_until')
    op.drop_column('users', 'last_active_at')
    op.drop_column('users', 'last_seen_at')
    # ### end Alembic commands ###
