"""add content body and ai sources (TASK-038)

Revision ID: f077eb002a48
Revises: fa1ce788eff5
Create Date: 2026-10-08 03:17:19.705328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f077eb002a48'
down_revision: Union[str, Sequence[str], None] = 'fa1ce788eff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketing_contents', sa.Column('body', sa.Text(), nullable=True))
    op.add_column('marketing_contents', sa.Column('body_ai_generated', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('marketing_contents', sa.Column('body_sources_json', sa.JSON(), nullable=True, comment='[{evidence_ref, document_title, seq}]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketing_contents', 'body_sources_json')
    op.drop_column('marketing_contents', 'body_ai_generated')
    op.drop_column('marketing_contents', 'body')
    # ### end Alembic commands ###
