"""add proposals (TASK-030)

Revision ID: 92e320c2fbff
Revises: 9aa52f11ad11
Create Date: 2026-10-08 00:48:55.235258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '92e320c2fbff'
down_revision: Union[str, Sequence[str], None] = '9aa52f11ad11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.Enum('SOLUTION', 'QUOTATION_NOTE', 'SERVICE_PLAN', 'COOPERATION', 'OTHER', name='proposal_kind'), nullable=False),
    sa.Column('status', sa.Enum('NONE', 'GENERATED', 'CONFIRMED', 'REJECTED', name='proposal_status'), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=True),
    sa.Column('target_name', sa.String(length=200), nullable=True),
    sa.Column('requirement', sa.Text(), nullable=True, comment='客户需求/背景，由人工填写；AI 不得添加原文没有的需求'),
    sa.Column('inputs_json', sa.JSON(), nullable=True, comment='生成时冻结的输入：{knowledge_hits:[...], business_data:{...}}'),
    sa.Column('content_json', sa.JSON(), nullable=True, comment='[{heading, body, basis}]'),
    sa.Column('confirmed_by', sa.String(length=64), nullable=True),
    sa.Column('confirmed_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.Column('llm_called', sa.Boolean(), nullable=False),
    sa.Column('llm_error', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proposals_customer', 'proposals', ['customer_id'], unique=False)
    op.create_index('ix_proposals_status', 'proposals', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_proposals_status', table_name='proposals')
    op.drop_index('ix_proposals_customer', table_name='proposals')
    op.drop_table('proposals')
    # ### end Alembic commands ###
