"""add risk_events (D11 frozen table)

Revision ID: 2a1e5d573abb
Revises: 5f4f336eda2e
Create Date: 2026-10-04 01:06:36.159402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2a1e5d573abb'
down_revision: Union[str, Sequence[str], None] = '5f4f336eda2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False, comment='所属客户；客户删除则其风险一并清除'),
    sa.Column('event_type', sa.Enum('POLICY_BLOCKED', 'AI_FAILED', 'MANUAL_FLAG', name='risk_event_type'), nullable=False),
    sa.Column('level', sa.Enum('LOW', 'ATTENTION', 'HIGH', name='risk_level'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'DISMISSED', name='risk_status'), nullable=False),
    sa.Column('source_type', sa.Enum('IMPORT', 'MANUAL', 'SYSTEM', name='evidence_source_type'), nullable=False, comment='风险由什么产生：IMPORT=导入数据 / MANUAL=人工 / SYSTEM=代码判定'),
    sa.Column('source_ref', sa.String(length=128), nullable=False, comment='来源唯一标识，如 customer_message:346'),
    sa.Column('trigger_text', sa.Text(), nullable=True, comment='触发摘要（D5：只作摘要，证据锚点用 message_id）'),
    sa.Column('reason', sa.String(length=512), nullable=True, comment='为什么判为风险（如「命中敏感策略：报价」）'),
    sa.Column('evidence_ref', sa.String(length=128), nullable=False, comment='证据锚点（D5：= customer_message:{id}）'),
    sa.Column('resolved_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('resolved_note', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), server_default=sa.text('now()'), nullable=False, comment='风险发生时间'),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_ref', name='uq_risk_events_source')
    )
    op.create_index('ix_risk_events_customer_status', 'risk_events', ['customer_id', 'status'], unique=False)
    op.create_index('ix_risk_events_level_status', 'risk_events', ['level', 'status'], unique=False)
    op.alter_column('customers', 'lifecycle_status',
               existing_type=mysql.ENUM('NEW', 'CONTACTED', 'REPLIED', 'ENGAGED', 'QUOTED', 'WON', 'LOST', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='生命周期状态；每次变更同时写一条 customer_events',
               existing_nullable=False,
               existing_server_default=sa.text("'NEW'"))
    op.alter_column('reports', 'content_json',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='生成时快照：指标 -> EvidenceValue 字典',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'content_json',
               existing_type=mysql.JSON(),
               comment='生成时快照：指标 -> EvidenceValue 字典',
               existing_nullable=False)
    op.alter_column('customers', 'lifecycle_status',
               existing_type=mysql.ENUM('NEW', 'CONTACTED', 'REPLIED', 'ENGAGED', 'QUOTED', 'WON', 'LOST', collation='utf8mb4_unicode_ci'),
               comment='生命周期状态；每次变更同时写一条 customer_events',
               existing_nullable=False,
               existing_server_default=sa.text("'NEW'"))
    op.drop_index('ix_risk_events_level_status', table_name='risk_events')
    op.drop_index('ix_risk_events_customer_status', table_name='risk_events')
    op.drop_table('risk_events')
    # ### end Alembic commands ###
