"""add knowledge base (TASK-026, §22)

Revision ID: 9aa52f11ad11
Revises: f01144d07b48
Create Date: 2026-10-04 06:24:52.405691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9aa52f11ad11'
down_revision: Union[str, Sequence[str], None] = 'f01144d07b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('doc_type', sa.Enum('PRODUCT', 'MARKET', 'USER', 'COMPETITOR', 'BUSINESS', 'OTHER', name='knowledge_doc_type'), nullable=False),
    sa.Column('source_type', sa.Enum('PASTED', 'UPLOAD', 'MANUAL', name='knowledge_source_type'), nullable=False),
    sa.Column('source_note', sa.String(length=500), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=False, comment='资料原文；切片通过 char_start/char_end 指向这里'),
    sa.Column('tags_json', sa.JSON(), nullable=True, comment='标签列表'),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True, comment='失效日；NULL=长期有效'),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_documents_active', 'knowledge_documents', ['is_active'], unique=False)
    op.create_index('ix_knowledge_documents_type', 'knowledge_documents', ['doc_type'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False, comment='在文档内的序号（从 1 起）'),
    sa.Column('content', sa.Text(), nullable=False, comment='切片正文'),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('evidence_ref', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_chunks_doc_seq', 'knowledge_chunks', ['document_id', 'seq'], unique=False)
    op.create_index('ix_knowledge_chunks_document', 'knowledge_chunks', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_chunks_document', table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_doc_seq', table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index('ix_knowledge_documents_type', table_name='knowledge_documents')
    op.drop_index('ix_knowledge_documents_active', table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    # ### end Alembic commands ###
