"""add customers and import_batches

Revision ID: 36e74cad14a0
Revises: 978f01c47fe5
Create Date: 2026-10-03 20:52:27.468780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = '36e74cad14a0'
down_revision: Union[str, Sequence[str], None] = '978f01c47fe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_sha256', sa.CHAR(length=64), nullable=False, comment='文件内容 sha256，用于 preview/commit 一致性与幂等'),
    sa.Column('status', sa.Enum('SUCCESS', 'PARTIAL', 'FAILED', name='import_batch_status'), nullable=False),
    sa.Column('source_type', sa.Enum('REAL', 'TEST', 'MANUAL', name='batch_source_type'), nullable=False),
    sa.Column('rows_total', sa.BigInteger(), nullable=False),
    sa.Column('rows_created', sa.BigInteger(), nullable=False),
    sa.Column('rows_deduplicated', sa.BigInteger(), nullable=False),
    sa.Column('rows_skipped', sa.BigInteger(), nullable=False),
    sa.Column('skipped_reasons_json', sa.JSON(), nullable=True),
    sa.Column('skipped_columns_json', sa.JSON(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('evidence_ref', sa.String(length=128), nullable=False, comment='证据锚点，由代码生成为 import_batch:{id}'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True, comment='只存数字（规范化后），空值一律为 NULL 不存空串'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='小写（规范化后），空值一律为 NULL 不存空串'),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('batch_id', sa.BigInteger(), nullable=True, comment='来源批次；MANUAL 录入为 NULL'),
    sa.Column('source_type', sa.Enum('REAL', 'TEST', 'MANUAL', name='customer_source_type'), nullable=False),
    sa.Column('evidence_ref', sa.String(length=128), nullable=True, comment='= import_batch:{batch_id}，代码生成'),
    sa.Column('dedupe_state', sa.Enum('CLEAN', 'PENDING_REVIEW', 'MERGED', name='customer_dedupe_state'), nullable=False),
    sa.Column('first_seen_at', mysql.DATETIME(fsp=6), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', mysql.DATETIME(fsp=6), server_default=sa.text('now()'), nullable=False, comment='命中即刷新：同一客户被导入命中就更新它'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_batch_id'), 'customers', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_batch_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('import_batches')
    # ### end Alembic commands ###
