"""add user profile fields and ai_providers (TASK-037)

Revision ID: fa1ce788eff5
Revises: 92e320c2fbff
Create Date: 2026-10-08 02:45:16.417981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fa1ce788eff5'
down_revision: Union[str, Sequence[str], None] = '92e320c2fbff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.Enum('DEEPSEEK', 'OPENAI', 'ANTHROPIC', 'QWEN', 'GEMINI', 'CUSTOM', name='ai_provider_kind'), nullable=False),
    sa.Column('protocol', sa.Enum('OPENAI_COMPATIBLE', 'ANTHROPIC', 'GEMINI', name='ai_protocol'), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_test_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind')
    )
    op.add_column('users', sa.Column('avatar_path', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('presence', sa.Enum('ONLINE', 'BUSY', 'OFFLINE', name='user_presence'), server_default='OFFLINE', nullable=False))
    op.add_column('users', sa.Column('theme', sa.Enum('SYSTEM', 'LIGHT', 'DARK', name='user_theme'), server_default='SYSTEM', nullable=False))
    op.add_column('users', sa.Column('email', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'email')
    op.drop_column('users', 'theme')
    op.drop_column('users', 'presence')
    op.drop_column('users', 'avatar_path')
    op.drop_table('ai_providers')
    # ### end Alembic commands ###
