"""add handover_state and customer_handover_events

TASK-005（并行线 5）：人工接管三态（D8：AUTO → HUMAN_REQUIRED → HUMAN_ACTIVE）。
  · customers.handover_state  —— 三态当前值，带 server_default 兜底存量行
  · customer_handover_events  —— 每次状态变化一条事件（AC5：不许只有当前值没有历史）

★ 本表是本 TASK 专属的；TASK-006 的通用事件表 customer_events 由另一条并行线拥有，
  两者都接在 36e74cad14a0 上、互不冲突。整合方式见 docs/HANDOVER_INTEGRATION.md。

Revision ID: 3ccb69d4e8a0
Revises: 36e74cad14a0
Create Date: 2026-10-03 22:15:26.033707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ccb69d4e8a0'
down_revision: Union[str, Sequence[str], None] = '36e74cad14a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_handover_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False, comment='所属客户；客户删除时事件一并删除（CASCADE）'),
    sa.Column('event_type', sa.Enum('HUMAN_REQUIRED', 'TAKEN_OVER', 'RESUMED', name='handover_event_type'), nullable=False),
    sa.Column('from_state', sa.Enum('AUTO', 'HUMAN_REQUIRED', 'HUMAN_ACTIVE', name='handover_from_state'), nullable=True, comment='迁移前状态（首条事件理论上仍有 from，留空只为容错）'),
    sa.Column('to_state', sa.Enum('AUTO', 'HUMAN_REQUIRED', 'HUMAN_ACTIVE', name='handover_to_state'), nullable=False),
    sa.Column('actor_type', sa.Enum('HUMAN', 'AI', 'SYSTEM', name='handover_actor_type'), nullable=False),
    sa.Column('source_type', sa.Enum('IMPORT', 'MANUAL', 'SYSTEM', name='handover_source_type'), nullable=False, comment='数据来源：人工操作=MANUAL；代码层判定=SYSTEM'),
    sa.Column('reason', sa.Text(), nullable=True, comment='为什么转人工（闸门命中原因 / 人工备注）'),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('evidence_ref', sa.String(length=128), nullable=False, comment='证据锚点，由代码生成 customer_handover_event:{id}'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_handover_events_customer_created', 'customer_handover_events', ['customer_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_customer_handover_events_customer_id'), 'customer_handover_events', ['customer_id'], unique=False)
    op.add_column('customers', sa.Column('handover_state', sa.Enum('AUTO', 'HUMAN_REQUIRED', 'HUMAN_ACTIVE', name='customer_handover_state'), server_default='AUTO', nullable=False, comment='人工接管三态：AUTO / HUMAN_REQUIRED / HUMAN_ACTIVE'))
    op.create_index(op.f('ix_customers_handover_state'), 'customers', ['handover_state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_handover_state'), table_name='customers')
    op.drop_column('customers', 'handover_state')
    op.drop_index(op.f('ix_customer_handover_events_customer_id'), table_name='customer_handover_events')
    op.drop_index('ix_customer_handover_events_customer_created', table_name='customer_handover_events')
    op.drop_table('customer_handover_events')
    # ### end Alembic commands ###
