"""add research focus field (TASK-042)

Revision ID: 4cf80be34404
Revises: e4af6ac94828
Create Date: 2026-10-08 04:36:21.960333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf80be34404'
down_revision: Union[str, Sequence[str], None] = 'e4af6ac94828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect_research', sa.Column('focus', sa.Text(), nullable=True, comment='研究要点（要查证的问题）；AI 可起草，不是证据'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospect_research', 'focus')
    # ### end Alembic commands ###
