"""add projects and project_customers (D28 unfreeze)

Revision ID: 32119d1c4b81
Revises: 7c1a033e3f26
Create Date: 2026-10-04 02:28:56.982847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '32119d1c4b81'
down_revision: Union[str, Sequence[str], None] = '7c1a033e3f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True, comment='项目编号；人工填，不自动生成'),
    sa.Column('status', sa.Enum('PLANNING', 'IN_PROGRESS', 'ON_HOLD', 'DELIVERED', 'CLOSED', 'CANCELLED', name='project_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='project_priority'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True, comment='进度 0~100；由人工填写，★ 不是按任务数推算'),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True, comment='计划完成日'),
    sa.Column('delivered_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True, comment='实际交付/结项时间'),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('evidence_ref', sa.String(length=128), nullable=True, comment='证据锚点 = project:{id}'),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_projects_dates', 'projects', ['start_date', 'due_date'], unique=False)
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    op.create_table('project_customers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'customer_id', name='uq_project_customer')
    )
    op.create_index('ix_project_customers_customer', 'project_customers', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_customers_customer', table_name='project_customers')
    op.drop_table('project_customers')
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_index('ix_projects_dates', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
