"""add customer_messages (TASK-003)

customer_messages —— D11 冻结 7 表中的第 3 张（沟通记录）。

★ sender_type 枚举里保留了 CUSTOMER，但 V1 站内没有真实客户渠道，
  **任何代码路径都不许写入 CUSTOMER**（D9 禁止伪造客户消息）。
  闸门在 services/messaging.py（服务层）+ api/routes/messages.py（接口层 400）。
★ evidence_ref 由代码生成为 customer_message:{id}，不是数据库默认值。

Revision ID: c63846e9f46f
Revises: 36e74cad14a0
Create Date: 2026-10-03 22:18:18.794611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c63846e9f46f'
down_revision: Union[str, Sequence[str], None] = '36e74cad14a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_type', sa.Enum('CUSTOMER', 'HUMAN', 'AI', 'SYSTEM', name='message_sender_type'), nullable=False),
    sa.Column('message_type', sa.Enum('CHAT', 'NOTE', 'IMPORT', name='message_type'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False, comment='消息正文（非空）'),
    sa.Column('source_type', sa.Enum('MANUAL', 'IMPORT', 'SYSTEM', name='message_source_type'), nullable=False, comment='写库必带：MANUAL=人工 / IMPORT=导入 / SYSTEM=系统'),
    sa.Column('evidence_ref', sa.String(length=128), nullable=False, comment='= customer_message:{id}，由代码生成（flush 拿到 id 后立刻回填）'),
    sa.Column('ai_status', sa.Enum('NONE', 'REQUESTED', 'REPLIED', 'FAILED', 'HUMAN_REQUIRED', name='message_ai_status'), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), server_default=sa.text('now()'), nullable=False, comment='消息时间（时间线排序键）'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_messages_customer_id'), 'customer_messages', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_messages_customer_id'), table_name='customer_messages')
    op.drop_table('customer_messages')
    # ### end Alembic commands ###
