"""add marketing_contents (D28 unfreeze)

Revision ID: 3cbfc0e50c74
Revises: 32119d1c4b81
Create Date: 2026-10-04 02:33:16.544231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3cbfc0e50c74'
down_revision: Union[str, Sequence[str], None] = '32119d1c4b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketing_contents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.Enum('ARTICLE', 'CASE_STUDY', 'WHITEPAPER', 'VIDEO', 'EVENT', 'LANDING_PAGE', 'OTHER', name='content_type'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'PUBLISHED', 'UNPUBLISHED', 'ARCHIVED', name='content_status'), nullable=False),
    sa.Column('channel', sa.Enum('WEBSITE', 'WECHAT', 'ZHIHU', 'VIDEO_CHANNEL', 'OFFLINE', 'OTHER', name='content_channel'), nullable=False),
    sa.Column('published_on', sa.Date(), nullable=True, comment='发布日期；未发布为 NULL（不是今天）'),
    sa.Column('view_count', sa.Integer(), nullable=True, comment='浏览量；NULL = 未统计（与 0 不同）'),
    sa.Column('author', sa.String(length=64), nullable=True, comment='作者/负责人'),
    sa.Column('url', sa.String(length=500), nullable=True, comment='内容链接'),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('evidence_ref', sa.String(length=128), nullable=True, comment='证据锚点 = content:{id}'),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_marketing_contents_published', 'marketing_contents', ['published_on'], unique=False)
    op.create_index('ix_marketing_contents_status', 'marketing_contents', ['status'], unique=False)
    op.create_index('ix_marketing_contents_type_channel', 'marketing_contents', ['content_type', 'channel'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_marketing_contents_type_channel', table_name='marketing_contents')
    op.drop_index('ix_marketing_contents_status', table_name='marketing_contents')
    op.drop_index('ix_marketing_contents_published', table_name='marketing_contents')
    op.drop_table('marketing_contents')
    # ### end Alembic commands ###
